/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c00100",
        "on-primary-fixed-variant": "#930100",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "secondary-container": "#464a4b",
        "on-primary-fixed": "#410000",
        "surface-container-low": "#1b1b1b",
        "primary-fixed-dim": "#ffb4a8",
        "secondary-fixed": "#e0e3e5",
        "error": "#ffb4ab",
        "primary": "#ffb4a8",
        "tertiary": "#b7c8e1",
        "primary-container": "#ff5540",
        "on-error-container": "#ffdad6",
        "on-secondary": "#2d3133",
        "on-surface-variant": "#ebbbb4",
        "on-tertiary": "#213145",
        "surface": "#131313",
        "on-secondary-container": "#b6b9bb",
        "inverse-surface": "#e2e2e2",
        "surface-container-high": "#2a2a2a",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#38485d",
        "on-tertiary-fixed": "#0b1c30",
        "outline": "#b18780",
        "outline-variant": "#603e39",
        "on-surface": "#e2e2e2",
        "surface-tint": "#ffb4a8",
        "secondary": "#c4c7c9",
        "surface-container": "#1f1f1f",
        "tertiary-fixed": "#d3e4fe",
        "on-background": "#e2e2e2",
        "on-tertiary-container": "#1a2b3e",
        "on-secondary-fixed": "#191c1e",
        "primary-fixed": "#ffdad4",
        "surface-bright": "#393939",
        "tertiary-fixed-dim": "#b7c8e1",
        "tertiary-container": "#8292aa",
        "on-secondary-fixed-variant": "#444749",
        "on-primary-container": "#5c0000",
        "surface-container-highest": "#353535",
        "secondary-fixed-dim": "#c4c7c9",
        "surface-variant": "#353535",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#303030",
        "on-primary": "#690100",
        "background": "#131313",
        "kinetic-red": "#FF0000"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "section-gap": "120px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "label-bold": ["Lexend", "sans-serif"],
        "headline-lg": ["Lexend", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "display-xl": ["Lexend", "sans-serif"],
        "lexend": ["Lexend", "sans-serif"]
      },
      fontSize: {
        "label-bold": ["14px", { "lineHeight": "1.0", "fontWeight": "700" }],
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-xl": ["80px", { "lineHeight": "1.0", "letterSpacing": "-0.04em", "fontWeight": "900" }]
      }
    },
  },
  plugins: [],
}
